Repository devlooped/SponsorLink, pull requests merged in 2024-09, with the labels that each got.

#319 Add an easy way to check for design-time builds
  samples/dotnet/Analyzer/StatusReportingGenerator.cs
  samples/dotnet/SponsorLink/AnalyzerOptionsExtensions.cs
Labels: enhancement

#325 Fix intellisense for SL resources
  samples/dotnet/SponsorLink.Analyzer.targets
Labels: tech debt

#326 Make the funding help url configurable via MSBuild
  samples/dotnet/Analyzer/Analyzer.csproj
  samples/dotnet/SponsorLink.Analyzer.targets
  samples/dotnet/SponsorLink/DiagnosticsManager.cs
  samples/dotnet/SponsorLink/SponsorLink.csproj
Labels: enhancement

#327 Add Grace period info reporting
  samples/dotnet/SponsorLink/DiagnosticsManager.cs
  samples/dotnet/SponsorLink/Resources.es-AR.resx
  samples/dotnet/SponsorLink/Resources.es.resx
  samples/dotnet/SponsorLink/Resources.resx
  samples/dotnet/SponsorLink/SponsorLink.csproj
  samples/dotnet/SponsorLink/SponsorLinkAnalyzer.cs
Labels: enhancement

#328 Add optional message to use as summary in sponsored APIs
  samples/dotnet/SponsorLink/Resources.es-AR.resx
  samples/dotnet/SponsorLink/Resources.es.resx
  samples/dotnet/SponsorLink/Resources.resx
Labels: documentation

#321 Fix dead links to the GitHub spec.
  docs/faq.md
  docs/index.md
  docs/spec/2.0.0-rc.1.md
  docs/spec/2.0.0-rc.2.md
  docs/spec/2.0.0.md
  src/Cli/readme.md
Labels: documentation

#330 Add overload to simplify getting or setting status
  samples/dotnet/Analyzer/StatusReportingGenerator.cs
  samples/dotnet/SponsorLink/DiagnosticsManager.cs
  samples/dotnet/SponsorLink/SponsorLink.cs
Labels: enhancement

#333 Enable UTF-8 output from GitHub CLI queries
  src/Commands/Process.cs
Labels: enhancement

#334 Add query to retrieve contributors for a given repository
  src/Commands/CliGraphQueryClient.cs
  src/Core/GraphQueries.cs
  src/Core/HttpGraphQueryClient.cs
  src/Tests/GraphQueriesTests.cs
Labels: enhancement

#338 Add command to fetch and discover nuget oss stats
  samples/dotnet/Analyzer/GraceApiAnalyzer.cs
  src/Cli/Program.cs
  src/Commands/App.cs
  src/Commands/CliGraphQueryClient.cs
  src/Commands/Commands.csproj
  src/Commands/NuGetStatsCommand.cs
Labels: enhancement

#339 Add support for considering oss authors/contribs as indirect sponsors
  .netconfig
  docs/_config.yml
  docs/_layouts/default.html
  docs/assets/js/oss.js
  docs/github/index.md
  docs/github/oss.md
  docs/spec.md
  docs/spec/2.0.1.md
  src/Commands/NuGetStatsCommand.cs
  src/Commands/SyncCommand.cs
  src/Core/GraphQueries.cs
  src/Core/Records.cs
  src/Core/SponsorLinkOptions.cs
  src/Core/SponsorType.cs
  src/Core/SponsorsManager.cs
  src/Tests/SponsorManagerTests.cs
  src/Tests/SyncCommandTests.cs
  src/Tests/System/Threading/Tasks/AsyncLazy.cs
  src/Web/Program.cs
Labels: enhancement

#343 Ensure output is UTF-8
  src/Cli/Program.cs
Labels: enhancement

#344 If starting browser fails, render the URI to navigate to
  src/Commands/GitHubAppAuthenticator.cs
Labels: enhancement

#345 Allow retrieving a shields.io badge with nuget stats
  src/Web/Stats.cs
  src/Web/Web.csproj
Labels: enhancement

#346 Allow fetching specific nuget owner stats
  src/Commands/NuGetStatsCommand.cs
  src/Web/Stats.cs
  src/Web/Webhook.cs
Labels: enhancement

#347 Add totals summary for nuget stats
  src/Core/Records.cs
Labels: enhancement

#348 Add exception propagation behavior with --exceptions
  src/Cli/Program.cs
Labels: enhancement

#349 Render globals totals after running nuget command
  src/Commands/NuGetStatsCommand.cs
Labels: enhancement

#350 Add user-friendly render of nuget stats totals
  src/Core/Core.csproj
  src/Core/Records.cs
Labels: enhancement

#351 Use new human readable metric summary values
  src/Commands/NuGetStatsCommand.cs
Labels: enhancement

#355 Add specific diagnostic/status for oss authors
  samples/dotnet/SponsorLink/DiagnosticsManager.cs
  samples/dotnet/SponsorLink/Resources.es.resx
  samples/dotnet/SponsorLink/Resources.resx
  samples/dotnet/SponsorLink/SponsorStatus.cs
  samples/dotnet/Tests/AnalyzerTests.cs
Labels: enhancement

#356 Allow easily copying markdown of OSS author badges
  docs/_config.yml
  docs/assets/js/oss.js
  src/Web/Stats.cs
Labels: enhancement
